package app.filipebezerra.placetoremind

import java.util.concurrent.TimeUnit


const val FOREGROUND_AND_BACKGROUND_PERMISSION_REQUEST_CODE = 33
const val FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
const val TURN_DEVICE_LOCATION_ON_REQUEST_CODE = 35
const val GRANT_LOCATION_PERMISSIONS_APP_DETAILS_SETTINGS_REQUEST_CODE = 36
const val TURN_DEVICE_LOCATION_ON_LOCATION_SOURCE_SETTINGS_REQUEST_CODE = 37

const val LOCATION_PERMISSION_INDEX = 0
const val BACKGROUND_LOCATION_PERMISSION_INDEX = 1

const val LOCATION_REQUEST_INTERVAL = 5000L
const val LOCATION_REQUEST_FASTEST_INTERVAL = 2500L

val TWO_MINUTES = TimeUnit.MINUTES.toNanos(2)